allowBuilds:
  nx: true
  unrs-resolver: true
  esbuild: true
  '@swc/core': true
  '@parcel/watcher': true
  less: true
  '@nestjs/core': false
  '@scarf/scarf': false
autoInstallPeers: true
strictPeerDependencies: false
